### ISSUE TITLE
Grabbing Open instances

### ISSUE THREAD

**Issue by woodape** [woodape/bl-switcher#1]
Currently, if either tint2 or conky is running without a `-c` argument followed by a full path, the pipemenu fails. This is because of the manner the `openConky` and `openTint2` functions parse the `ps` shell command to retrieve the config files of open conkies and tint2's. This function is necessary but needs to be fixed so that should a conky or tint2 not be run with a config file, the pipemenu doesn't fail.

Additionally, this should be fixed by allowing conkies or tint2s which are launched without full-path configs to still be killed off.

**Comment by smacz42** [comment]
I can envision three scenarios that this script may have to face.

1) If I read the man page correctly, the only way that `ps` would show a `conky` command without *anything else* would be if it was ran only as `conky` and had used one of the following:

* `${sysconfdir}/conky/conky.conf` (`${sysconfdir}` typically being `/etc`)
* `~/.conkyrc`

Also, there would only be one of those that could be used at any given time with the bare-bones command. Because if `~/.conkyrc` exists, it is chosen and ran instead of the default located in `/etc`. This gives you no constants or identifiers of any kind in the output of `ps` (that I can tell), but it will only *ever* be one of two files. Can we do anything with that certainty?

2) Running from a config file, but not a full-path config will give you at least two constants. One, it will have an `.conkyrc` extension (or at least we *should* be able to assume this), and two, it will be ran with a flag of '-c'. I would assume that would be enough for a regex to handle some string parsing or something (I wish I had a good grasp on what I was talking about :P). 

3) Other than specifying `-c` for a config file, one is able to pass command-line arguments to configure a conky on-the-fly as it were. That means no `.conkyrc` extension and no `-c` flag. How these should be portrayed in the menu has the potential to become quite convoluted, and pkill is giving me trouble with killing them (command substitution errors) if I try to base them off of the output of `ps -C conky -o cmd` (`pkill "${output}"`). I'll leave this one open-ended, but I will say that using processes (/proc) has the potential to be a much more elegant (yet complex) solution.

Keep in mind that these hang-ups are just for conkys that are started outside of the script. The script itself is robust when it works within it's own devices. Maybe another option would be to attempt to integrate any conkys started externally into the `session.log` file. Just thinking out loud here.

**Comment by woodape** [comment]
Right on all accounts, other than with (2), I don't think we should be assuming that non-full-path conkies will be run with a config file that ends with the extension `.conkyrc`, and I don't think it would be a good idea to integrate externally started conkies into the `session.log` file. After all this file is just a list of paths of `.conkyrc` files. If the conky isn't run with a path, there would be nothing to put in this file unless the entrie program was re-written to accomodate some other type of `session.log` file.

I think the way that we'll have to deal with this is by using each conky instance's unique `pid` to kill it, and calling conkies with no config file `Unknown Conky 0` , `Unknown Conky 1` etc. in the pipemenu. All conkies, config file or not, will have a unique PID and `kill` can kill them based on this. I'm trying to figure this out now. have to incorporate dictionaries somehow...

**Comment by woodape** [comment]
Please check the fix-issue1 branch. I'm confident it fixes the issue.

**Comment by smacz42** [comment]
Brilliant. And what a quick fix too. I did the write-up in [this post](http://crunchbang.org/forums/viewtopic.php?pid=423659#p423659), but in summation, I'd say it's ready to be merged back into master as the final fix for this issue.
